apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: iceberg-sink
  namespace: lakehouse-demo
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.tabular.iceberg.connect.IcebergSinkConnector
  tasksMax: 1
  config:
    topics: "server1.inventory.customers,server1.inventory.orders"
    iceberg.tables: "lakehouse.inventory.customers,lakehouse.inventory.orders"
    iceberg.tables.auto-create-enabled: "true"
    iceberg.tables.evolve-schema-enabled: "true"
    iceberg.catalog.type: "rest"
    iceberg.catalog.uri: "http://iceberg-rest:8181"
    iceberg.catalog.s3.endpoint: "http://minio:9000"
    iceberg.catalog.s3.access-key-id: "admin"
    iceberg.catalog.s3.secret-access-key: "password"
    iceberg.catalog.warehouse: "s3://warehouse/"
    key.converter: "io.apicurio.registry.serde.avro.AvroKafkaDeserializer"
    value.converter: "io.apicurio.registry.serde.avro.AvroKafkaDeserializer"
    value.converter.apicurio.registry.url: "http://apicurio-registry:8080/apis/registry/v3"
