apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: lakehouse-demo
data:
  iceberg.properties: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://iceberg-rest:8181
    iceberg.file-format=PARQUET
    fs.native-s3.enabled=true
    s3.endpoint=http://minio:9000
    s3.region=us-east-1
    s3.aws-access-key=admin
    s3.aws-secret-key=password
    s3.path-style-access=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: lakehouse-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
        - name: trino
          image: trinodb/trino:439
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: catalog
              mountPath: /etc/trino/catalog/iceberg.properties
              subPath: iceberg.properties
      volumes:
        - name: catalog
          configMap:
            name: trino-config
---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: lakehouse-demo
spec:
  selector:
    app: trino
  ports:
    - port: 8080
      targetPort: 8080
